stages:
- name: image and deploy
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: jb/numball
      pushRemote: true
      registry: docker-registry.docker-registry.192.168.2.108.xip.io
  when:
    branch: {}
    event: {}
timeout: 60
branch:
  include:
  - master
notification: {}
