stages:
- name: image and deploy
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: numball:1.1
      pushRemote: true
      registry: docker.jaebae.net
  when:
    branch: {}
    event: {}
- name: deploy app
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch:
  include:
  - master
notification: {}
