stages:
- name: image and deploy
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: jb/numball
      pushRemote: true
      registry: docker.jaebae.net
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    branch: {}
    event: {}
timeout: 60
branch:
  include:
  - master
notification: {}
