kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: numball-deployment
spec:
  revisionHistoryLimit: 5
  minReadySeconds: 10
  selector:
    matchLabels:
      app: numball      
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 3
  template:
    metadata:
      labels:
        app: numball
    spec:
      containers:
        - name: numball
          image: docker.jaebae.net/jb/numball:latest
          imagePullSecrets:
            - name: docker-jaebae-net
